language: node_js
node_js:
  - "6.10"
script:
  # run build script specified in package.json
  - npm run build -- --prod
  # call script for deploying of produced artifacts
  - bash ./.travis-deploy.sh
