language: node_js
node_js:
  - "6.10"

addons:
  firefox: latest

cache:
  directories:
     - ./node_modules

before_install:
  # set no display
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  # run test script
  - npm run test -- --single-run --browsers Firefox --reporters dots

after_failure: "cat npm-debug.log"

before_deploy:
  # run build script specified in package.json
  - npm run build -- --prod --base-href /tetris/

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
