language: node_js
node_js:
  - "6.10"
sudo: required

before_install:
  # set no display
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  # install chrome
  - export CHROME_BIN=$HOME/.chrome/chromium/chrome-linux/chrome
  - bash ./.travis-chrome-install.sh
  # run test script
  - npm run test -- --single-run --browsers=ChromeNoSandbox

before_deploy:
  # run build script specified in package.json
  - npm run build -- --prod --base-href /tetris/

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
