language: node_js
node_js:
  - "6.10"
script:
  # run test script
  - npm run test -- --single-run --browser ChromeNoSandbox
  # run build script specified in package.json
  - npm run build -- --prod --base-href /tetris/
  # call script for deploying of produced artifacts
  - bash ./.travis-deploy.sh

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
